class BibleConstants {
  static const List<Map<String, dynamic>> bibleVersions = [
    {
      'id': 'rv1909',
      'language': 'es',
      'name': 'Reina-Valera 1909',
      'abbreviation': 'RV1909',
      'description': 'La Biblia clásica en español, dominio público',
      'isPublicDomain': true,
    },
    {
      'id': 'rv1865',
      'language': 'es',
      'name': 'Reina-Valera 1865',
      'abbreviation': 'RV1865',
      'description': 'Versión histórica en español, dominio público',
      'isPublicDomain': true,
    },
    {
      'id': 'kjv',
      'language': 'en',
      'name': 'King James Version',
      'abbreviation': 'KJV',
      'description': 'The classic English Bible, public domain',
      'isPublicDomain': true,
    },
    {
      'id': 'web',
      'language': 'en',
      'name': 'World English Bible',
      'abbreviation': 'WEB',
      'description': 'Modern public domain English translation',
      'isPublicDomain': true,
    },
    {
      'id': 'asv',
      'language': 'en',
      'name': 'American Standard Version',
      'abbreviation': 'ASV',
      'description': 'Classic American translation, public domain',
      'isPublicDomain': true,
    },
  ];

  static const List<Map<String, dynamic>> bibleBooks = [
    // Old Testament - Antiguo Testamento
    {'id': 1,  'name_es': 'Génesis',       'name_en': 'Genesis',       'chapters': 50,  'testament': 'OT', 'abbreviation': 'Gen'},
    {'id': 2,  'name_es': 'Éxodo',         'name_en': 'Exodus',        'chapters': 40,  'testament': 'OT', 'abbreviation': 'Exo'},
    {'id': 3,  'name_es': 'Levítico',      'name_en': 'Leviticus',     'chapters': 27,  'testament': 'OT', 'abbreviation': 'Lev'},
    {'id': 4,  'name_es': 'Números',       'name_en': 'Numbers',       'chapters': 36,  'testament': 'OT', 'abbreviation': 'Num'},
    {'id': 5,  'name_es': 'Deuteronomio',  'name_en': 'Deuteronomy',   'chapters': 34,  'testament': 'OT', 'abbreviation': 'Deu'},
    {'id': 6,  'name_es': 'Josué',         'name_en': 'Joshua',        'chapters': 24,  'testament': 'OT', 'abbreviation': 'Jos'},
    {'id': 7,  'name_es': 'Jueces',        'name_en': 'Judges',        'chapters': 21,  'testament': 'OT', 'abbreviation': 'Jdg'},
    {'id': 8,  'name_es': 'Rut',           'name_en': 'Ruth',          'chapters': 4,   'testament': 'OT', 'abbreviation': 'Rut'},
    {'id': 9,  'name_es': '1 Samuel',      'name_en': '1 Samuel',      'chapters': 31,  'testament': 'OT', 'abbreviation': '1Sa'},
    {'id': 10, 'name_es': '2 Samuel',      'name_en': '2 Samuel',      'chapters': 24,  'testament': 'OT', 'abbreviation': '2Sa'},
    {'id': 11, 'name_es': '1 Reyes',       'name_en': '1 Kings',       'chapters': 22,  'testament': 'OT', 'abbreviation': '1Ki'},
    {'id': 12, 'name_es': '2 Reyes',       'name_en': '2 Kings',       'chapters': 25,  'testament': 'OT', 'abbreviation': '2Ki'},
    {'id': 13, 'name_es': '1 Crónicas',    'name_en': '1 Chronicles',  'chapters': 29,  'testament': 'OT', 'abbreviation': '1Ch'},
    {'id': 14, 'name_es': '2 Crónicas',    'name_en': '2 Chronicles',  'chapters': 36,  'testament': 'OT', 'abbreviation': '2Ch'},
    {'id': 15, 'name_es': 'Esdras',        'name_en': 'Ezra',          'chapters': 10,  'testament': 'OT', 'abbreviation': 'Ezr'},
    {'id': 16, 'name_es': 'Nehemías',      'name_en': 'Nehemiah',      'chapters': 13,  'testament': 'OT', 'abbreviation': 'Neh'},
    {'id': 17, 'name_es': 'Ester',         'name_en': 'Esther',        'chapters': 10,  'testament': 'OT', 'abbreviation': 'Est'},
    {'id': 18, 'name_es': 'Job',           'name_en': 'Job',           'chapters': 42,  'testament': 'OT', 'abbreviation': 'Job'},
    {'id': 19, 'name_es': 'Salmos',        'name_en': 'Psalms',        'chapters': 150, 'testament': 'OT', 'abbreviation': 'Psa'},
    {'id': 20, 'name_es': 'Proverbios',    'name_en': 'Proverbs',      'chapters': 31,  'testament': 'OT', 'abbreviation': 'Pro'},
    {'id': 21, 'name_es': 'Eclesiastés',   'name_en': 'Ecclesiastes',  'chapters': 12,  'testament': 'OT', 'abbreviation': 'Ecc'},
    {'id': 22, 'name_es': 'Cantares',      'name_en': 'Song of Solomon','chapters': 8,  'testament': 'OT', 'abbreviation': 'SoS'},
    {'id': 23, 'name_es': 'Isaías',        'name_en': 'Isaiah',        'chapters': 66,  'testament': 'OT', 'abbreviation': 'Isa'},
    {'id': 24, 'name_es': 'Jeremías',      'name_en': 'Jeremiah',      'chapters': 52,  'testament': 'OT', 'abbreviation': 'Jer'},
    {'id': 25, 'name_es': 'Lamentaciones', 'name_en': 'Lamentations',  'chapters': 5,   'testament': 'OT', 'abbreviation': 'Lam'},
    {'id': 26, 'name_es': 'Ezequiel',      'name_en': 'Ezekiel',       'chapters': 48,  'testament': 'OT', 'abbreviation': 'Eze'},
    {'id': 27, 'name_es': 'Daniel',        'name_en': 'Daniel',        'chapters': 12,  'testament': 'OT', 'abbreviation': 'Dan'},
    {'id': 28, 'name_es': 'Oseas',         'name_en': 'Hosea',         'chapters': 14,  'testament': 'OT', 'abbreviation': 'Hos'},
    {'id': 29, 'name_es': 'Joel',          'name_en': 'Joel',          'chapters': 3,   'testament': 'OT', 'abbreviation': 'Joe'},
    {'id': 30, 'name_es': 'Amós',          'name_en': 'Amos',          'chapters': 9,   'testament': 'OT', 'abbreviation': 'Amo'},
    {'id': 31, 'name_es': 'Abdías',        'name_en': 'Obadiah',       'chapters': 1,   'testament': 'OT', 'abbreviation': 'Oba'},
    {'id': 32, 'name_es': 'Jonás',         'name_en': 'Jonah',         'chapters': 4,   'testament': 'OT', 'abbreviation': 'Jon'},
    {'id': 33, 'name_es': 'Miqueas',       'name_en': 'Micah',         'chapters': 7,   'testament': 'OT', 'abbreviation': 'Mic'},
    {'id': 34, 'name_es': 'Nahúm',         'name_en': 'Nahum',         'chapters': 3,   'testament': 'OT', 'abbreviation': 'Nah'},
    {'id': 35, 'name_es': 'Habacuc',       'name_en': 'Habakkuk',      'chapters': 3,   'testament': 'OT', 'abbreviation': 'Hab'},
    {'id': 36, 'name_es': 'Sofonías',      'name_en': 'Zephaniah',     'chapters': 3,   'testament': 'OT', 'abbreviation': 'Zep'},
    {'id': 37, 'name_es': 'Hageo',         'name_en': 'Haggai',        'chapters': 2,   'testament': 'OT', 'abbreviation': 'Hag'},
    {'id': 38, 'name_es': 'Zacarías',      'name_en': 'Zechariah',     'chapters': 14,  'testament': 'OT', 'abbreviation': 'Zec'},
    {'id': 39, 'name_es': 'Malaquías',     'name_en': 'Malachi',       'chapters': 4,   'testament': 'OT', 'abbreviation': 'Mal'},
    // New Testament - Nuevo Testamento
    {'id': 40, 'name_es': 'Mateo',         'name_en': 'Matthew',       'chapters': 28,  'testament': 'NT', 'abbreviation': 'Mat'},
    {'id': 41, 'name_es': 'Marcos',        'name_en': 'Mark',          'chapters': 16,  'testament': 'NT', 'abbreviation': 'Mar'},
    {'id': 42, 'name_es': 'Lucas',         'name_en': 'Luke',          'chapters': 24,  'testament': 'NT', 'abbreviation': 'Luk'},
    {'id': 43, 'name_es': 'Juan',          'name_en': 'John',          'chapters': 21,  'testament': 'NT', 'abbreviation': 'Joh'},
    {'id': 44, 'name_es': 'Hechos',        'name_en': 'Acts',          'chapters': 28,  'testament': 'NT', 'abbreviation': 'Act'},
    {'id': 45, 'name_es': 'Romanos',       'name_en': 'Romans',        'chapters': 16,  'testament': 'NT', 'abbreviation': 'Rom'},
    {'id': 46, 'name_es': '1 Corintios',   'name_en': '1 Corinthians', 'chapters': 16,  'testament': 'NT', 'abbreviation': '1Co'},
    {'id': 47, 'name_es': '2 Corintios',   'name_en': '2 Corinthians', 'chapters': 13,  'testament': 'NT', 'abbreviation': '2Co'},
    {'id': 48, 'name_es': 'Gálatas',       'name_en': 'Galatians',     'chapters': 6,   'testament': 'NT', 'abbreviation': 'Gal'},
    {'id': 49, 'name_es': 'Efesios',       'name_en': 'Ephesians',     'chapters': 6,   'testament': 'NT', 'abbreviation': 'Eph'},
    {'id': 50, 'name_es': 'Filipenses',    'name_en': 'Philippians',   'chapters': 4,   'testament': 'NT', 'abbreviation': 'Phi'},
    {'id': 51, 'name_es': 'Colosenses',    'name_en': 'Colossians',    'chapters': 4,   'testament': 'NT', 'abbreviation': 'Col'},
    {'id': 52, 'name_es': '1 Tesalonicenses','name_en': '1 Thessalonians','chapters': 5,'testament': 'NT', 'abbreviation': '1Th'},
    {'id': 53, 'name_es': '2 Tesalonicenses','name_en': '2 Thessalonians','chapters': 3,'testament': 'NT', 'abbreviation': '2Th'},
    {'id': 54, 'name_es': '1 Timoteo',     'name_en': '1 Timothy',     'chapters': 6,   'testament': 'NT', 'abbreviation': '1Ti'},
    {'id': 55, 'name_es': '2 Timoteo',     'name_en': '2 Timothy',     'chapters': 4,   'testament': 'NT', 'abbreviation': '2Ti'},
    {'id': 56, 'name_es': 'Tito',          'name_en': 'Titus',         'chapters': 3,   'testament': 'NT', 'abbreviation': 'Tit'},
    {'id': 57, 'name_es': 'Filemón',       'name_en': 'Philemon',      'chapters': 1,   'testament': 'NT', 'abbreviation': 'Phm'},
    {'id': 58, 'name_es': 'Hebreos',       'name_en': 'Hebrews',       'chapters': 13,  'testament': 'NT', 'abbreviation': 'Heb'},
    {'id': 59, 'name_es': 'Santiago',      'name_en': 'James',         'chapters': 5,   'testament': 'NT', 'abbreviation': 'Jas'},
    {'id': 60, 'name_es': '1 Pedro',       'name_en': '1 Peter',       'chapters': 5,   'testament': 'NT', 'abbreviation': '1Pe'},
    {'id': 61, 'name_es': '2 Pedro',       'name_en': '2 Peter',       'chapters': 3,   'testament': 'NT', 'abbreviation': '2Pe'},
    {'id': 62, 'name_es': '1 Juan',        'name_en': '1 John',        'chapters': 5,   'testament': 'NT', 'abbreviation': '1Jo'},
    {'id': 63, 'name_es': '2 Juan',        'name_en': '2 John',        'chapters': 1,   'testament': 'NT', 'abbreviation': '2Jo'},
    {'id': 64, 'name_es': '3 Juan',        'name_en': '3 John',        'chapters': 1,   'testament': 'NT', 'abbreviation': '3Jo'},
    {'id': 65, 'name_es': 'Judas',         'name_en': 'Jude',          'chapters': 1,   'testament': 'NT', 'abbreviation': 'Jud'},
    {'id': 66, 'name_es': 'Apocalipsis',   'name_en': 'Revelation',    'chapters': 22,  'testament': 'NT', 'abbreviation': 'Rev'},
  ];

  static const Map<String, String> languageNames = {
    'es': 'Español',
    'en': 'English',
  };
}
